import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function Home () {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
        <link rel="stylesheet" href="https://unpkg.com/@picocss/pico@latest/css/pico.classless.min.css"/>
        <title>Hello, world!</title>
        <meta charset="utf-8"/>
      </Head>
      <main className={styles.main} data-theme="light">
      <h1>Hello, world!</h1>
      <form>

  <div class="grid">

    <label for="firstname">
      First name
      <input type="text" id="firstname" name="firstname" placeholder="First name" required/>
    </label>

    <label for="lastname">
      Last name
      <input type="text" id="lastname" name="lastname" placeholder="Last name" required/>
    </label>

  </div>


  <label for="email">Email address</label>
  <input type="email" id="email" name="email" placeholder="Email address" required/>
  <small>We'll never share your email with anyone else.</small>

  <button type="submit">Submit</button>

</form>
      <div class="grid">
  <div>1</div>
  <div>2</div>
  <div>3</div>
  <div>4</div>
  <div>5</div>
  <div>6</div>
</div>

      <blockquote>
  "Maecenas vehicula metus tellus, vitae congue turpis hendrerit non. 
  Nam at dui sit amet ipsum cursus ornare."
  <footer>
    <cite>- Phasellus eget lacinia</cite>
  </footer>
</blockquote>
      </main>
    </>
  )
}
